{"uuid": "4a78dd08-b197-415d-a6ec-c47d30af0fbb", "children": ["4ed5c8b9-884f-42e4-aabd-aacffc2f5f9c"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1718615476153, "stop": 1718615476153}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\IKHLAS\\PycharmProjects\\pythonHybrid Framework\\PySelenium\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\IKHLAS\\PycharmProjects\\pythonHybrid Framework\\PySelenium\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\IKHLAS\\PycharmProjects\\pythonHybrid Framework\\Tests\\conftest.py\", line 13, in log_on_failure\n    if item.rep_call.failed:\n"}, "start": 1718615479058, "stop": 1718615479122}], "start": 1718615476153, "stop": 1718615479122}